// src/constants/employees.ts
// Daftar nama pegawai untuk dropdown form

export const EMPLOYEE_NAMES = [
  "Mukti Riadi, S.ST, M.Si",
  "Triyandar Habsi, S.ST, M.M.",
  "Tatang Dwiyatmoko SST",
  "Muhammad Fathoni, S.Kom",
  "Lahmodin Oktanata, SP",
  "Jongen Nugraha, S.E",
  "Three Febrianty Kesuma, S.P",
  "Nafitalia, S.Si",
  "Yulia Gumanti, S.M",
  "Hida Kusmawati, S.ST",
  "Riska Kuzaimah, S.E",
  "Tiara Maureen, S.Tr.Stat",
  "Ferdiansyah Gunawan, S.A.P",
  "Venny Delviari, S.A.P",
  "Indah Mulyati, S.M, S.E.",
  "Popy Hislami, S.Tr.Stat, M.M.",
  "Fahmi Idris, A.Md",
  "Bondan Damarsari, A.Md",
  "Ronatal Christian",
  "Deddy Argo Riawan",
  "Arya Damar Prakarsa, S.Tr.Stat",
  "Amran Pratama Putra, S.Tr.Stat",
  "Wildhan Nizar Ramadhan, S.Tr.Stat",
  "Syifa Rizqi Qatrunnada, S.Tr.Stat",
  "Cahya Astadan Saqti, A.Md.Stat",
  "Chelsy Alisia Fareta, A.Md",
  "Hidayati Aulia Fitri, S.Tr.Stat",
  "Nadhea Fairuz Harly, S.ST",
  "Eka Putri Lailatul Cahyani, S.Tr.Stat",
  "Hamam Hadinata Widodo, S.Tr.Stat",
] as const;
